// Generated by sdkgen go-cli target.
package main

import (
	"fmt"
	"strings"

	eng "github.com/boru-lang/boru/eng/go"
	sdk "github.com/voxgig-sdk/apicurio-registry-sdk/go"
)

func registerSDKWords(r *eng.Registry, client *sdk.ApicurioRegistrySDK) {
	for _, op := range []string{"list", "load", "update"} {
		op := op
		single := eng.Signature{
			Args:      []*eng.Type{eng.TAtom},
			QuoteArgs: map[int]bool{0: true},
			Impl: eng.Go(func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				return runOp(client, op, nil, args[0])
			}),
			Returns:    []*eng.Type{eng.TAny},
			BarrierPos: eng.BarrierAllForward,
		}
		dual := eng.Signature{
			Args:      []*eng.Type{eng.TAny, eng.TAtom},
			QuoteArgs: map[int]bool{1: true},
			Impl: eng.Go(func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				q := args[0]
				return runOp(client, op, &q, args[1])
			}),
			Returns:    []*eng.Type{eng.TAny},
			BarrierPos: eng.BarrierAllForward,
		}
		r.RegisterNativeFunc(eng.NativeFunc{
			Name:       op,
			Signatures: []eng.Signature{single, dual},
		})
	}
}

func runOp(client *sdk.ApicurioRegistrySDK, op string, query *eng.Value, entityAtom eng.Value) ([]eng.Value, error) {
	entityName, err := eng.AsAtom(entityAtom)
	if err != nil {
		return nil, fmt.Errorf("%s: entity argument is not an atom: %w", op, err)
	}
	ent, err := entityFor(client, entityName)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", op, err)
	}

	var arg map[string]any
	if query != nil {
		arg, err = queryToMap(*query)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", op, err)
		}
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(arg, nil)
	case "load":
		result, err = ent.Load(arg, nil)
	case "update":
		result, err = ent.Update(arg, nil)
	default:
		return nil, fmt.Errorf("unknown op %q", op)
	}
	if err != nil {
		return nil, err
	}
	return []eng.Value{eng.FromNative(extractData(result))}, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.ApicurioRegistrySDK, name string) (sdk.ApicurioRegistryEntity, error) {
	switch strings.ToLower(name) {
	case "admin":
		return client.Admin(nil), nil
	case "agent":
		return client.Agent(nil), nil
	case "agent_card":
		return client.AgentCard(nil), nil
	case "ai_catalog":
		return client.AiCatalog(nil), nil
	case "ard_explore":
		return client.ArdExplore(nil), nil
	case "ard_search":
		return client.ArdSearch(nil), nil
	case "artifact":
		return client.Artifact(nil), nil
	case "artifact_reference":
		return client.ArtifactReference(nil), nil
	case "artifact_rule":
		return client.ArtifactRule(nil), nil
	case "artifact_type":
		return client.ArtifactType(nil), nil
	case "branch":
		return client.Branch(nil), nil
	case "comment":
		return client.Comment(nil), nil
	case "configuration_property":
		return client.ConfigurationProperty(nil), nil
	case "consumer_version_heatmap":
		return client.ConsumerVersionHeatmap(nil), nil
	case "content":
		return client.Content(nil), nil
	case "contract":
		return client.Contract(nil), nil
	case "contract_rule":
		return client.ContractRule(nil), nil
	case "contract_rule_set":
		return client.ContractRuleSet(nil), nil
	case "create_artifact":
		return client.CreateArtifact(nil), nil
	case "deprecation_readiness":
		return client.DeprecationReadiness(nil), nil
	case "download_ref":
		return client.DownloadRef(nil), nil
	case "git_op":
		return client.GitOp(nil), nil
	case "git_ops_status":
		return client.GitOpsStatus(nil), nil
	case "git_ops_validate_task":
		return client.GitOpsValidateTask(nil), nil
	case "global_rule":
		return client.GlobalRule(nil), nil
	case "group":
		return client.Group(nil), nil
	case "group_rule":
		return client.GroupRule(nil), nil
	case "kafka_sql":
		return client.KafkaSql(nil), nil
	case "metadata":
		return client.Metadata(nil), nil
	case "odcs_contract_result":
		return client.OdcsContractResult(nil), nil
	case "odcs_contract_summary":
		return client.OdcsContractSummary(nil), nil
	case "reference_graph":
		return client.ReferenceGraph(nil), nil
	case "role_mapping":
		return client.RoleMapping(nil), nil
	case "rule":
		return client.Rule(nil), nil
	case "searched_branch":
		return client.SearchedBranch(nil), nil
	case "searched_group":
		return client.SearchedGroup(nil), nil
	case "system_info":
		return client.SystemInfo(nil), nil
	case "usage_summary":
		return client.UsageSummary(nil), nil
	case "user_info":
		return client.UserInfo(nil), nil
	case "user_interface_config":
		return client.UserInterfaceConfig(nil), nil
	case "version":
		return client.Version(nil), nil
	case "well_known":
		return client.WellKnown(nil), nil
	case "wrapped_version_state":
		return client.WrappedVersionState(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// queryToMap converts a boru Value (Map or Scalar) into the
// `map[string]any` shape the SDK expects. Maps are unwrapped via
// eng.ToNative. Scalars are wrapped as {"id": <value>} so the
// shorthand `load 1 book` becomes `load {id:1} book`.
func queryToMap(v eng.Value) (map[string]any, error) {
	if v.Parent.ConformsTo(eng.TMap) {
		m, ok := eng.ToNative(v).(map[string]any)
		if !ok {
			return nil, fmt.Errorf("query map could not be unwrapped")
		}
		return m, nil
	}
	if v.Parent.ConformsTo(eng.TScalar) {
		return map[string]any{"id": eng.ToNative(v)}, nil
	}
	return nil, fmt.Errorf("query must be a Map or Scalar, got %s", v.Parent)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with the underlying record via .Data().
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}
